image: docker:stable-dind

stages:
  # - test
  - build
  # - deploy

variables:
  IMAGE_NAME: "gcr.io/dabenxiang226/kbc_chatbot"

  # ------------build------------
build_prod_image_job_gen:
  stage: build
  image: google/cloud-sdk
  tags:
    - docker
  only:
    - tags
  script:
    - docker version
    - echo "$RELEASE_CREDENTIALS" > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud auth configure-docker
    - DOCKER_BUILDKIT=1 docker build --build-arg VERSION=$CI_COMMIT_TAG --build-arg COMMITSHA=$CI_COMMIT_SHA -f ./build/Dockerfile -t $IMAGE_NAME:$CI_COMMIT_TAG . --pull
    - docker image push "$IMAGE_NAME:$CI_COMMIT_TAG"
